# cloudbuild.yaml
steps:
  # Step 1: Install Node.js dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    env:
      - 'NPM_CONFIG_UPDATE_NOTIFIER=false'

  # Step 2: Build the Next.js application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      # Next.js client-side variables (prefixed with NEXT_PUBLIC_)
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}'
      - 'GOOGLE_GENAI_API_KEY=${_GOOGLE_GENAI_API_KEY}'
      - 'ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY}'
    secretEnv: [
      '_NEXT_PUBLIC_FIREBASE_API_KEY',
      '_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN', 
      '_NEXT_PUBLIC_FIREBASE_PROJECT_ID',
      '_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
      '_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
      '_NEXT_PUBLIC_FIREBASE_APP_ID',
      '_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID',
      '_GOOGLE_GENAI_API_KEY',
      '_ANTHROPIC_API_KEY'
    ]

  # Step 3: Deploy to Firebase Hosting and Functions
  - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    args: ['deploy', '--project=${_FIREBASE_PROJECT_ID}']
    secretEnv: ['_FIREBASE_PROJECT_ID']

options:
  logging: CLOUD_LOGGING_ONLY

# Define substitutions for secrets, mapping them to Secret Manager secret names
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: _NEXT_PUBLIC_FIREBASE_API_KEY
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: _NEXT_PUBLIC_FIREBASE_PROJECT_ID
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: _NEXT_PUBLIC_FIREBASE_APP_ID
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest
      env: _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    - versionName: projects/${PROJECT_ID}/secrets/FIREBASE_PROJECT_ID/versions/latest
      env: _FIREBASE_PROJECT_ID
    - versionName: projects/${PROJECT_ID}/secrets/GOOGLE_GENAI_API_KEY/versions/latest
      env: _GOOGLE_GENAI_API_KEY
    - versionName: projects/${PROJECT_ID}/secrets/ANTHROPIC_API_KEY/versions/latest
      env: _ANTHROPIC_API_KEY